name: Check File Deploy 2025
on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
    inputs:
      check-file:
        description: 'CHECK FILE'
        type: string
        required: true
        default: ''

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:      
      - name: Create Workspace
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/workspace
          set -o allexport
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
          export TARGET_FORCE_PREBUILT_KERNEL=false
          echo "PREBUILT_KERNEL=false" >> $GITHUB_ENV
          if [[ `which git` ]]; then
          echo -e "\n`git --version`\n";
          git config --global core.longpaths true
          git config --global core.protectNTFS false
          git config --global http.postBuffer 524288000 # Increase post buffer size (example value in bytes)
          git config --global http.lowSpeedLimit 0      # Disable low speed limit
          git config --global http.lowSpeedTime 999999  # Increase low speed time threshold
          else
          echo -e "\nGit needed installing now....\n";
          sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -yq git >/dev/null;
          git config --global core.longpaths true
          git config --global core.protectNTFS false
          git config --global http.postBuffer 524288000 # Increase post buffer size (example value in bytes)
          git config --global http.lowSpeedLimit 0      # Disable low speed limit
          git config --global http.lowSpeedTime 999999  # Increase low speed time threshold
          fi
          set +e
        continue-on-error: true
        
      - name: Check File
        if: inputs.check-file != ''
        uses: Tec4Sho/check-file-action@master
        with:
          filename: ${{ inputs.check-file }}
          dirname: workspace
          rootdir: false
          content: true
        continue-on-error: true
