name: TWRP Builder 2025
on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'MANIFEST BRANCH'
        required: true
        default: 'twrp-9.0'
        type: choice
        options:
        - twrp-14.1
        - twrp-12.1
        - twrp-11
        - twrp-9.0
      DEVICE_TREE:
        description: 'DEVICE TREE'
        required: true
        default: 'https://github.com/Tec4Sho/android_device_alps_tb8163p3_bsp.git'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE TREE BRANCH'
        required: true
        default: 'android-9.0'
      DEVICE_PATH:
        description: 'DEVICE PATH'
        required: true
        default: 'device/alps/tb8163p3_bsp'
      DEVICE_NAME:
        description: 'DEVICE NAME'
        required: true
        default: 'tb8163p3_bsp'
      BUILD_TARGET:
        description: 'BUILD TARGET'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot
      CPPCHECK_OPTS:
        description: 'CPPCHECK OPTS'
        type: string
        required: false
        default: ''
      CACHING_ENABLED:
        description: ': ENABLE CACHING'
        type: boolean
        required: false
        default: 'false'
      CLEAN_ENVIRONMENT:
        description: ': CLEAN ENVIRONMENT'
        type: boolean
        required: false
        default: 'true'
      MAXIMIZE_BUILD_SPACE:
        description: ': MAXIMIZE BUILD SPACE'
        type: boolean
        required: false
        default: 'true'
        
jobs:
  build:
    name: ${{ github.event.inputs.BUILD_TARGET }} by ${{ github.actor }} | ${{ github.event.repository.updated_at }}
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.TWRP }}
    permissions:
      contents: write
    steps:
    - name: Build Inputs
      run: |
        echo "::group::User Environment Variables"
        echo "Displaying main variables/inputs."
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree: ${{ github.event.inputs.DEVICE_TREE }}"
        echo "Device Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}image"     
        echo "::endgroup::";
        
     # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Check Workspace & Remove Pkg*
      run: |
        echo "Listing 100 largest runner packages"
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        echo 
        echo "Removing some large packages"
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
      continue-on-error: true
      
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Cleanup Environment 
      if: github.event.inputs.CLEAN_ENVIRONMENT == 'true'
      uses: rokibhasansagar/slimhub_actions@main
      with:
        retain: "browser_all,clang,gcc,g++,python,ccache,repo,git,git-repo,powershell"
      # That's it! Now use your normal steps  

    - name: Maximize Build Space
      if: github.event.inputs.MAXIMIZE_BUILD_SPACE == 'true'
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 11000 # Example: Reserve 12 GB for the root directory
        swap-size-mb: 2048 # Example: Reserve 4 GB for swap file
        remove-dotnet: 'true' # Example: Remove the .NET SDK to free space 
      continue-on-error: true

    - name: Create Workspace
      run: |
        mkdir -p workspace
        mkdir -p workspace/${{ github.event.inputs.DEVICE_PATH }}
        mkdir -p workspace/kernel/alps/tb8163p3_bsp
        cd workspace
        
     # Setup for dual git cloning
    - name: Checkout Recovery Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: ./${{ github.event.inputs.DEVICE_PATH }}

    - name: Checkout Kernel Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.actor }}/android_kernel_mt8163
        path: ./kernel/alps/tb8163p3_bsp
        
    - name: Restore Workspace
      if: github.event.inputs.CACHING_ENABLED == 'true'
      id: restore-workspace-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ./workspace/.repo
          ./workspace/kernel
          ./workspace/device
          ~/opt/hostedtoolcache
          ~/var/cache/apt/archives
        key: ${{ runner.os }}-workspace-${{ github.event.pull_request.head.sha || github.sha }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-workspace-${{ github.event.pull_request.head.sha || github.sha }}
          ${{ runner.os }}-workspace
          ${{ runner.os }}
        enableCrossOsArchive: true
      continue-on-error: true
        
    - name: Prepare The Environment
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install g++ clang ccache git git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 unzip fontconfig bc repo m4 libssl-dev kmod device-tree-compiler libx11-dev lib32z1-dev cppcheck git-lfs libelf-dev libxml2 rsync adb fastboot ncurses-doc libasound2-doc gnome-shell lib32stdc++6-10-dbg libx32stdc++6-10-dbg notification-daemon opus-tools pulseaudio wx3.0-doc gettext distcc gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib lib32ncurses5-dev x11proto-core-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libgflags-dev python3
        sudo add-apt-repository universe
        sudo apt-get -y install libncurses5 libtinfo5
      continue-on-error: true

    - name: Install OpenJDK
      if: steps.restore-workspace-cache.outputs.cache-hit != 'true'
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8

    - name: Install Git-Repo
      if: steps.restore-workspace-cache.outputs.cache-hit != 'true'
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
        
    - name: Check Build Tree
      uses: haya14busa/action-cond@v1.2.1
      id: buildtree
      with:
        cond: ${{ inputs.MANIFEST_BRANCH == '11' || inputs.MANIFEST_BRANCH == '12.1' }}
        if_true: aosp
        if_false: omni

    - name: Check Manifest Branch
      uses: haya14busa/action-cond@v1
      id: manifest
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1'  || github.event.inputs.MANIFEST_BRANCH == 'twrp-14.1' }}
        if_true: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
        if_false: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git
      
    - name: Initialize Repo
      if: steps.restore-workspace-cache.outputs.cache-hit != 'true'
      run: |
        cd workspace
        export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
        git config --global --add safe.directory ${GITHUB_WORKSPACE}/workspace
        git config --global user.email "${GitHubMail}"
        git config --global user.name "${GitHubName}"
        git config --global credential.helper store
        repo init --depth=1 -u ${{ steps.manifest.outputs.value }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      
    - name: Repo Sync
      if: steps.restore-workspace-cache.outputs.cache-hit != 'true'
      run: |
        cd workspace
        repo sync -c -j$(nproc --all) --force-sync
      continue-on-error: false

    - name: Clone Device Tree
      if: steps.restore-workspace-cache.outputs.cache-hit != 'true'
      run: |
        cd workspace
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        git clone https://github.com/Tec4Sho/android_kernel_mt8163.git -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./kernel/alps/tb8163p3_bsp
        echo "##### NOTE: Not Building From Cached Files  #####"
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
      continue-on-error: true

    - name: Install Python 2
      if: github.event.inputs.MANIFEST_BRANCH != 'twrp-11' && github.event.inputs.MANIFEST_BRANCH != 'twrp-12.1'  && github.event.inputs.MANIFEST_BRANCH != 'twrp-14' && steps.cache-build-restore.outputs.cache-hit != 'true'
      run: |
        sudo apt-get -y install python2
        cd /usr/bin
        sudo ln -sf python2 python
      continue-on-error: true

    - name: Save Workspace
      if: github.event.inputs.CACHING_ENABLED == 'true' && steps.restore-workspace-cache.outputs.cache-hit != 'true'
      id: save-workspace-cache
      uses: actions/cache/save@v4
      with:
        path: |
          ./workspace/.repo
          ./workspace/kernel
          ./workspace/device
          ~/opt/hostedtoolcache
          ~/var/cache/apt/archives
        key: ${{ steps.restore-workspace-cache.outputs.cache-primary-key }}
        enableCrossOsArchive: true
      continue-on-error: true
        
    - name: Check Build Makefile
      run: |
        cd workspace
        if [ -f ${{ github.event.inputs.DEVICE_PATH }}/twrp_${{ github.event.inputs.DEVICE_NAME}}.mk ]; then
            echo "DEVICE_MAKEFILE=twrp_${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        elif [ -f ${{ github.event.inputs.DEVICE_PATH }}/omni_${{ github.event.inputs.DEVICE_NAME}}.mk ]; then
            echo "DEVICE_MAKEFILE=omni_${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        else
            echo "No build makefile file found!"
            exit 1
        fi
        echo "-----------------------------------------------------"
        #find / -name archives -type d -maxdepth 8 -print 2>/dev/null
        echo "-----------------------------------------------------"

    - name: Check Build Space 
      run: |
        echo '### Before clean ###'
        sudo df -h
        echo
        echo '### cleaning build environment space ###'
        # clean build environment space
        sudo apt-get remove -y kubectl powershell firefox # docker-ce dotnet-sdk-8.0 dotnet-runtime-8.0 azure-cli 
        # sudo rm -vrf /usr/share/dotnet/ >/dev/null
        echo '### After clean ###' 
        sudo df -h
        cd workspace
        echo
        echo '### Workspace directory ###'
        sudo df . -h
        echo
        echo '### large files in workspace dir ###'
        sudo find . -type f -size +100M -exec du -ha {} +
      continue-on-error: true

    - name: Check Workspace Contents
      run: |
        du . -h -d 2
        echo "########## Copying Dockerfile ......"
        cp -vf ./workspace/${{ github.event.inputs.DEVICE_PATH }}/Dockerfile ./workspace
      continue-on-error: true

    - name: Cppcheck Build Files
      if: github.event.inputs.CPPCHECK_OPTS != ''
      uses: tonybaloney/cppcheck-action@master
      with:
        path: ./workspace/Dockerfile
        opts: -v --force --enable=all -j 2 --xml --output-file=workflow_build_report --report-progress ${{ github.event.inputs.CPPCHECK_OPTS }}
      continue-on-error: true

    - name: Publish Cppcheck Report
      if: github.event.inputs.CPPCHECK_OPTS != ''
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: "${{ github.event.inputs.DEVICE_TREE_BRANCH }}" # your branch name goes here
      continue-on-error: true

    - name: Export Build Settings
      run: |
        export USE_NINJA=true
        export CPU_SSE42=false
        export CLANG_TRIPLE=arm-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
        export ALLOW_MISSING_DEPENDENCIES=true
        export LLVM_ENABLE_THREADS=OFF
        export BOARD_VNDK_RUNTIME_DISABLE=true
        export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
        export BRANCH=android-9.0
        # export CROSS_COMPILE=arm-linux-androidkernel-
        export DEFCONFIG=tb8163p3_bsp_defconfig
        # export EXTRA_CMDS='bootopt=64S3,32N2,32N2 androidboot.selinux=permissive androidboot.init_fatal_reboot_target=recovery console=ttyS0,921600n1 root=/dev/ram androidboot.hardware=mt8163 firmware_class.path=/vendor/firmware build=06_12_24(gA1A470FC) lcm_id=4000 brightness=8388613 avdd=52 vcom=46 skip_initramfs ro rootwait init=/init root=PARTUUID=e7099731-95a6-45a6-a1e5-1b6aba032cf1 androidboot.verifiedbootstate=orange androidboot.atm=disabled androidboot.meta_log_disable=0 androidboot.dtbo_idx=0 printk.disable_uart=0 bootprof.pl_t=1680 bootprof.lk_t=7245 boot_reason=4 androidboot.serialno=SC5SKNLBEYIRBMR4 androidboot.bootreason=reboot mrdump_ddrsv=yes mrdump_rsvmem=0x56000000,0x400000,0x42000000,0x17f740,0x54000000,0x80000'
        export KERNEL_DIR=kernel/alps/tb8163p3_bsp 
        export LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN=prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin
        export FILES="arch/arm/boot/zImage vmlinux System.map"
        export STOP_SHIP_TRACEPRINTK=1
        export CONFIG_INIT_ENV_ARG_LIMIT=32
        export CROSS_COMPILE="arm-eabi-"
        export CONFIG_FS_ENCRYPTION=N
        export ARCH=arm
        export CC=clang
        export LC_ALL=C
      continue-on-error: true
    
    - name: Setup Compiler = Clang-12
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: 'clang-12'
      continue-on-error: true
        
    - name: Building ${{ github.event.inputs.BUILD_TARGET }} Image
      run: |
        echo "Started Build On $CURRENT_DATE"
        cd workspace
        set +eo
        source build/envsetup.sh
        ninja -t restat
        lunch ${{ env.DEVICE_MAKEFILE }}-eng && make clean && make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      
    - name: Build Date ${{ github.event.repository.updated_at }} # Output will be use in Release
      run: |
        echo "Done building your ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        DEVICE_TREE_URL="${{ github.event.inputs.DEVICE_TREE }}"
        if [[ "${DEVICE_TREE_URL}" == *.git ]]; then
          DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
        fi
        echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV
        
    - name: Checking if ${{ github.event.inputs.BUILD_TARGET }} Exist
      run: |
        cd workspace
        if [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img ]; then
            echo "RECOVERY_TYPE=recovery" >> $GITHUB_ENV
            echo "recovery.img file found!"
            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
        elif [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/boot.img ]; then
            echo "RECOVERY_TYPE=boot" >> $GITHUB_ENV
            echo "boot.img file found!"
            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
        elif [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img ]; then
            echo "RECOVERY_TYPE=vendor_boot" >> $GITHUB_ENV
            echo "vendor_boot.img file found!"
            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
        else
            echo "ERROR: No ${{ github.event.inputs.BUILD_TARGET }} image found! Exiting ...."
            exit 1
        fi
        
    - name: Include ${{ github.event.inputs.BUILD_TARGET }} Installer
      run: |
        if [ ${{ github.event.inputs.BUILD_TARGET }} == 'recovery' ]; then
          export USE_RECOVERY_INSTALLER=true
          export RECOVERY_INSTALLER_PATH=bootable/recovery/installer
          cd workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/
          wget https://github.com/kinguser981/recovery-installer/releases/download/zip/recovery-installer.zip
          zip -ur recovery-installer.zip ${{ env.RECOVERY_TYPE }}.img
        fi
      continue-on-error: true
        
    - name: Uploading ${{ github.event.inputs.BUILD_TARGET }} Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery-installer.zip
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ env.RECOVERY_TYPE }}.img
        name: Unofficial TWRP for Alps ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
        
    - name: Release ramdisk-${{ github.event.inputs.BUILD_TARGET }}
      uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/ramdisk-recovery.*  
        name: Unofficial TWRP for Alps ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Target: ${{ github.event.inputs.BUILD_TARGET}}.img
          Device: [Device Tree/Branch](${{ env.DEVICE_TREE_URL }}/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ env.DEVICE_TREE_URL }}/commit/${{ env.COMMIT_ID }}) during building.
          MD5 (img): ${{ env.MD5_IMG }}
          
